# Site settings
title: Aamer-Sadiq
description: 'Technical Short Stories'
url: 'https://aamersadiq.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Aamer Sadiq'
  email: aamer_au@yahoo.com
  twitter_username: aamer_sadiq
  # facebook_username: joshgerdes
  github_username:  aamersadiq
  linkedin_username:  aamersadiq

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 20
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
